In [1]:
#Импортируем необходиимых библиотек для реализации парсинга
from selenium import webdriver
from selenium_stealth import stealth # делает похожим на настоящего пользователя
from bs4 import BeautifulSoup
from selenium.webdriver.common.keys import Keys
from time import sleep
from tqdm import tqdm
import pandas as pd
import numpy as np
import keyboard

In [2]:
# Загрузка имо
imos=pd.read_excel('D:\Стас\Ученье - Свет\Оценка\Аспирантура\Видео по NN, Data mining, ABC и т.д\Распределение Гаусса, регрессия\Python\!Наработки\Парсинг по судам/Флитфото.xlsx', sheet_name = 1)
imos=imos.drop(['Unnamed: 0'], axis=1)
imos.head(20)

        ИМО
0   9916795
1   9916800
2   8722238
3   8227719
4   7106657
5   8606939
6   7532844
7   8746765
8   8721284
9   7384663
10  8728191
11  8969343
12  8869294
13  6827010
14  6518229
15  9053830
16  6824408
17  8521048
18  7032662
19  7039995

In [24]:
options = webdriver.ChromeOptions()
options.add_argument("start_maximized")

options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
driver = webdriver.Chrome(options=options, executable_path=r"C:\Python\chromedriver.exe")
#chromedriver должен соответствовать актуальной версии chrom, тут используется версия chrom 107.0.5304.121
#версия chromedriver - 107.0.5304.62 (все работает!)

stealth(driver,
        languages=["en-US", "en"],
        vendor="Google Inc.",
        platform="Win32",
        webgl_vendor="Intel Iris OpenGL Engine",
        fix_hairline=True,
        )

url = f"https://lk.rs-class.org/regbook/regbookVessel?ln=ru" #загружаем русскоязычную версию сайта
driver.get(url)

C:\Users\skapr\AppData\Local\Temp\ipykernel_10516\57469797.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(options=options, executable_path=r"C:\Python\chromedriver.exe")

In [6]:
#Ячейка для ввода ИМО
link_all = []
for r in tqdm(range(len(imos)), 'Сбор ссылок'):
    try:
        #print(imos.iloc[r]['ИМО'])
        imo = str(imos.iloc[r]['ИМО'])

        #imo = 8801632
        #driver.find_element_by_tag_name('input') #поиск через тег
        #driver.find_element_by_class_name("form-control") #поиск через класс
        #driver.find_element_by_xpath("/html/body/div[2]/div[4]/form/div/div[2]/div/input") #поиск через full XPath
        input_tab = driver.find_element_by_css_selector("#namer") #поиск input через selector
        input_tab.send_keys(imo) #вносим в ячейку ИМО
        button = driver.find_element_by_xpath('//button[@type="submit"]') #находим элемент кнопки Search через xpath
        button.click() #нажимаем кнопку Search
        #input_tab.send_keys(Keys.ENTER)
        sleep(1) #спим 1 секунду

        #Вытаскиваем ссылку
        #Внимание!! Проблема с поиском элемента (тега) может быть вызвана с языком сайта rus/eng
        link = driver.find_element_by_class_name('table') #выгружаем класс table (таблица с первоначальными данными)
        links = link.find_element_by_tag_name('a').get_attribute("href") #вытаскиваем ссылку
        link_all.append(links) #складываем ее в словарь

        driver.get(url)
        sleep(1) #спим 1 секунду
        #keyboard.send("Alt+left")
        #input_tab.click()
        #input_tab.clear()
        #input_tab.sendKeys(textContent)
    except:
        links = imo #если номер имо отсутствует в базе, то указываем его вместо ссылки
        link_all.append(links)
        driver.get(url)
        sleep(1) #спим 1 секунду
        continue

Сбор ссылок:   0%|                                                                           | 0/10555 [00:00<?, ?it/s]C:\Users\skapr\AppData\Local\Temp\ipykernel_14632\189829976.py:12: DeprecationWarning: find_element_by_css_selector is deprecated. Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead
  input_tab = driver.find_element_by_css_selector("#namer") #поиск input через selector
C:\Users\skapr\AppData\Local\Temp\ipykernel_14632\189829976.py:14: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  button = driver.find_element_by_xpath('//button[@type="submit"]') #находим элемент кнопки Search через xpath
C:\Users\skapr\AppData\Local\Temp\ipykernel_14632\189829976.py:21: DeprecationWarning: find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead
  link = driver.find_element_by_class_name('table') #выгружаем класс table (таблица с первоначальными данными)
Сбор ссылок:   0%|                                                                 | 2/10555 [00:05<7:43:25,  2.63s/it]C:\Users\skapr\AppData\Local\Temp\ipykernel_14632\189829976.py:22: DeprecationWarning: find_element_by_tag_name is deprecated. Please use find_element(by=By.TAG_NAME, value=name) instead
  links = link.find_element_by_tag_name('a').get_attribute("href") #вытаскиваем ссылку
Сбор ссылок: 100%|█████████████████████████████████████████████████████████████| 10555/10555 [7:50:39<00:00,  2.68s/it]

In [7]:
link_all

['9916795',
 '9916800',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=840255',
 '8227719',
 '7106657',
 '8606939',
 '7532844',
 '8746765',
 '8721284',
 '7384663',
 '8728191',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=992782',
 '8869294',
 '6827010',
 '6518229',
 '9053830',
 '6824408',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=862485',
 '7032662',
 '7039995',
 '7735020',
 '7932769',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=871376',
 '7517040',
 '8857083',
 '6521422',
 '7526675',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=831843',
 '9175195',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=860691',
 '8700199',
 '7426241',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=992213',
 '7306063',
 '7303504',
 '8324646',
 '7725568',
 '6405018',
 '8607127',
 '7424425',
 '6424442',
 '8030180',
 '9369459',
 '7932771',
 '7733620',
 '9343819',
 '7605811',
 '7204851',
 '8721349',
 '7303516',
 '7029809',
 '8205307',
 '7719595',
 '7923653',
 '8844995',
 '8912792',
 '8845676',
 '8833922',
 '7124518',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1016118',
 '7626451',
 '7702566',
 '8826266',
 '6823727',
 '7600768',
 '7616781',
 '8878764',
 '7324247',
 '7359838',
 '8902307',
 '8613762',
 '8613774',
 '7907790',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=882205',
 '6925903',
 '8606874',
 '7348750',
 '7909889',
 '8845652',
 '7015195',
 '8856493',
 '8723294',
 '6860579',
 '8200876',
 '8722721',
 '7800605',
 '7040293',
 '8802480',
 '8869244',
 '8868513',
 '8728828',
 '8869232',
 '9312121',
 '7300928',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=990865',
 '9503744',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=873920',
 '8700101',
 '8925579',
 '8868501',
 '7359357',
 '7021596',
 '8227721',
 '7044598',
 '6814843',
 '7831068',
 '8412390',
 '6718051',
 '5209780',
 '8521995',
 '8207032',
 '8722678',
 '7010858',
 '8228323',
 '8869282',
 '6415867',
 '8869608',
 '8723397',
 '7533991',
 '7040059',
 '7909891',
 '9304899',
 '7637668',
 '8522030',
 '7413531',
 '8131740',
 '8100624',
 '7040621',
 '8913435',
 '9014640',
 '9281140',
 '7726720',
 '8313532',
 '8201313',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991392',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=832329',
 '7922013',
 '7728998',
 '7728986',
 '7932666',
 '8522092',
 '8602830',
 '8899770',
 '7319838',
 '7353286',
 '6708848',
 '7741184',
 '8926107',
 '7333274',
 '7311367',
 '8835994',
 '8837904',
 '8858788',
 '5186330',
 '6929375',
 '8406585',
 '8839433',
 '7319266',
 '8421951',
 '6875988',
 '8326266',
 '7605794',
 '7114537',
 '8401420',
 '8607311',
 '7328061',
 '6419552',
 '7628447',
 '8623949',
 '8218615',
 '7384699',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=997344',
 '7730147',
 '8003761',
 '7355272',
 '5142750',
 '8314598',
 '8216722',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991862',
 '7528520',
 '7608643',
 '7435709',
 '9076260',
 '7514555',
 '8227355',
 '7939822',
 '6701137',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=830164',
 '9135834',
 '9133733',
 '8607244',
 '7039969',
 '9101871',
 '8913461',
 '6707416',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=920765',
 '9640475',
 '9640463',
 '7617620',
 '7406150',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=821023',
 '7343164',
 '7032595',
 '8521000',
 '9016961',
 '8314653',
 '8918978',
 '7116456',
 '8225565',
 '8719073',
 '8607347',
 '7110115',
 '6521587',
 '9016923',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=893133',
 '9256913',
 '8328707',
 '8139015',
 '8606666',
 '8607361',
 '7740934',
 '6914033',
 '6854805',
 '8026634',
 '8422838',
 '9053842',
 '6871504',
 '7233448',
 '9086708',
 '8324751',
 '7427623',
 '7506895',
 '6824460',
 '7418672',
 '9080493',
 '7035353',
 '7514921',
 '7406198',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=901497',
 '7907776',
 '9044358',
 '6900587',
 '7701213',
 '7607936',
 '8752075',
 '8033792',
 '7630153',
 '7608655',
 '8874328',
 '8311924',
 '8813972',
 '7218319',
 '7001247',
 '8926509',
 '9427990',
 '8827002',
 '7009392',
 '7039268',
 '8311895',
 '9133721',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=895008',
 '7605823',
 '8730118',
 '8606795',
 '7832725',
 '7604843',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=883034',
 '7301154',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=894240',
 '7040267',
 '8928155',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=850098',
 '7042370',
 '8223062',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=902240',
 '7384675',
 '7106865',
 '7104233',
 '7001912',
 '7630426',
 '7300930',
 '8319859',
 '7384211',
 '7040463',
 '8225204',
 '7507859',
 '8846278',
 '8721741',
 '7029952',
 '8854213',
 '6860414',
 '6929404',
 '8721674',
 '9286815',
 '8866333',
 '7384651',
 '7722592',
 '7605847',
 '8874330',
 '7119317',
 '7315416',
 '9443504',
 '8101927',
 '7040449',
 '7533953',
 '7532818',
 '8422761',
 '7337866',
 '8923260',
 '7711397',
 '9222417',
 '8892019',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=900193',
 '6810627',
 '6925082',
 '6871138',
 '7040633',
 '8131829',
 '7427063',
 '8421200',
 '7037375',
 '7514543',
 '8884220',
 '9564190',
 '9110339',
 '7348762',
 '7329443',
 '8871974',
 '7021780',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=651879',
 '8203543',
 '8846383',
 '8314615',
 '7035274',
 '5248932',
 '7012246',
 '8218689',
 '7107390',
 '7315143',
 '6915726',
 '7909803',
 '6503573',
 '6614188',
 '6620979',
 '9521899',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=851577',
 '8522169',
 '8606721',
 '8926652',
 '8314639',
 '7384716',
 '7125081',
 '8417170',
 '6704347',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=992401',
 '9088392',
 '9901374',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=800224',
 '8301022',
 '7814711',
 '7384704',
 '9813565',
 '9823821',
 '8128169',
 '6910362',
 '6705262',
 '8606680',
 '7418579',
 '9540730',
 '9540742',
 '8615019',
 '9335707',
 '7211294',
 '8878336',
 '5336040',
 '7405704',
 '7335935',
 '9194270',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991486',
 '8721923',
 '7040102',
 '5290715',
 '7130153',
 '7421722',
 '7436624',
 '7420584',
 '8963636',
 '8926030',
 '7111561',
 '7062325',
 '8028307',
 '8421896',
 '7347445',
 '7111444',
 '6823985',
 '7608813',
 '7221407',
 '7038044',
 '8520446',
 '6521757',
 '8728787',
 '7044392',
 '8960725',
 '7800318',
 '6417322',
 '7510676',
 '8879964',
 '7640952',
 '7040724',
 '8726703',
 '8719114',
 '8126563',
 '8201416',
 '8201430',
 '7436404',
 '8131776',
 '8729303',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=891577',
 '8517097',
 '7904853',
 '7630062',
 '7040891',
 '7030030',
 '6723393',
 '7435345',
 '8607220',
 '8120387',
 '8882806',
 '7337799',
 '8228763',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=993280',
 '8031043',
 '7362639',
 '9076478',
 '5150616',
 '8723062',
 '6703733',
 '7044823',
 '8912833',
 '9008043',
 '8202733',
 '8913459',
 '6516726',
 '7039983',
 '5342415',
 '5211630',
 '8017011',
 '7643849',
 '7007540',
 '7001209',
 '7733474',
 '7226639',
 '6919136',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=990393',
 '8897253',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=992890',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=990386',
 '6912023',
 '7513850',
 '5353062',
 '8976358',
 '7387237',
 '7040475',
 '8834005',
 '8871613',
 '9057214',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=950328',
 '7524299',
 '7920364',
 '8503072',
 '9481893',
 '8878790',
 '7023572',
 '8111788',
 '7925778',
 '7643928',
 '7040437',
 '7352476',
 '7359371',
 '9201542',
 '7506883',
 '7337804',
 '6873112',
 '7514579',
 '8325896',
 '7627766',
 '8606800',
 '7630244',
 '8516756',
 '7418476',
 '7125029',
 '8507573',
 '8311900',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=800559',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=892476',
 '8833934',
 '6901359',
 '8931205',
 '8607141',
 '8884244',
 '8645571',
 '8315516',
 '9100774',
 '9883637',
 '9101792',
 '7012375',
 '7012301',
 '8714592',
 '8926042',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1000942',
 '7421203',
 '7023738',
 '8228335',
 '7107883',
 '7237315',
 '7044574',
 '8035025',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=931238',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1003460',
 '8034899',
 '8014784',
 '8319823',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1015203',
 '6802864',
 '6404155',
 '7359826',
 '9842190',
 '9899002',
 '9064126',
 '7733400',
 '8966133',
 '7430917',
 '6726307',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=993097',
 '7107388',
 '7703895',
 '6608220',
 '6521240',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=960211',
 '7703883',
 '9940186',
 '9057317',
 '9245457',
 '5010268',
 '8936528',
 '7006596',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=941121',
 '6930001',
 '7415058',
 '6500961',
 '7832294',
 '8835932',
 '7945651',
 '7832282',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991078',
 '6916859',
 '8522004',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=940896',
 '8724470',
 '8868020',
 '8330463',
 '9848625',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991467',
 '8877904',
 '8831572',
 '9159907',
 '8034904',
 '9137466',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1014152',
 '7124415',
 '5016755',
 '9801146',
 '9848596',
 '7337438',
 '7111913',
 '7303437',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=880869',
 '7044536',
 '7045293',
 '9178109',
 '7030860',
 '7023788',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1001290',
 '8212922',
 '7102443',
 '7909449',
 '8226349',
 '7328504',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=874073',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1014213',
 '7832919',
 '7336147',
 '7044562',
 '6923541',
 '8934087',
 '8314586',
 '8858609',
 '8723749',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=999584',
 '6851528',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=852680',
 '8016873',
 '8724274',
 '6802228',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1014332',
 '7627730',
 '7630074',
 '8872887',
 '7044366',
 '9751901',
 '6703549',
 '8031160',
 '7906904',
 '6703563',
 '8729494',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=997505',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=990866',
 '6914069',
 '9836177',
 '7418490',
 '7740843',
 '7529756',
 '8847143',
 '7038147',
 '7606932',
 '7039658',
 '7533135',
 '8422709',
 '7052337',
 '8826204',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1015265',
 '8201387',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=886441',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=900047',
 '7638222',
 '7733424',
 '5047326',
 '9137480',
 '8889282',
 '7822768',
 '6825634',
 '6415142',
 '9836206',
 '7423055',
 '7319486',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=721573',
 '9277981',
 '7045176',
 '8314627',
 '8014253',
 '6800189',
 '7053305',
 '8623925',
 '9121156',
 '6928565',
 '9906386',
 '7008960',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=10017',
 '6701371',
 '7418660',
 '7107352',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991636',
 '6521812',
 '6827424',
 '9940198',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=711285',
 '7328530',
 '6906672',
 '8857992',
 '8646276',
 '8763206',
 '7328475',
 '7045073',
 '7337878',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=891115',
 '8892320',
 '6806987',
 '7362392',
 '8897095',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=931129',
 '7942192',
 '7516046',
 '8859914',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=980060',
 '7645146',
 '8727018',
 '8509208',
 '8723256',
 '7045085',
 '7045097',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1000055',
 '8031312',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=901111',
 '5383225',
 '8936891',
 '7311408',
 '8722159',
 '9530307',
 '9929065',
 '6503872',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=992819',
 '6827876',
 '8131752',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=905407',
 '7025994',
 '6853605',
 '9886237',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=998263',
 '6421464',
 '7367847',
 '7300942',
 '8707757',
 '8226284',
 '7337969',
 '7514957',
 '7941174',
 '7733436',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1013664',
 '8226961',
 '7945687',
 '7831903',
 '8902280',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1014849',
 '8031196',
 '7343114',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1015377',
 '7044718',
 '7115696',
 '6905642',
 '7733448',
 '7608837',
 '7337933',
 '7115816',
 '6404507',
 '8700149',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=930752',
 '7101932',
 '8031184',
 '7020243',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=910021',
 '7524421',
 '6419526',
 '7231878',
 '7305069',
 '7005011',
 '9836191',
 '9943968',
 '70451904',
 '6616801',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=991435',
 '8101939',
 '7418751',
 '7044639',
 '8845688',
 '7427013',
 '6514493',
 '8227862',
 '7427025',
 '7427049',
 '7235460',
 '8811699',
 '8225620',
 '6815287',
 '7310612',
 '7101944',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1015697',
 '7406186',
 '7016668',
 '7430797',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=873371',
 '7712236',
 '7324285',
 '7325772',
 '8016457',
 '6900630',
 '6910609',
 '6702806',
 '7831056',
 '8131659',
 '8131673',
 '8131635',
 '8722850',
 '6503339',
 '7730197',
 '7422130',
 '7384209',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=821771',
 '6914215',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=990389',
 '7022069',
 '7129752',
 '9876359',
 '8522054',
 '8729559',
 '6605840',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=892512',
 '6900084',
 '8628157',
 '7032466',
 '9137454',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1000785',
 '9945148',
 '7004603',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=851349',
 '8728529',
 '8985593',
 '6926385',
 '7052557',
 '5160506',
 '8424238',
 '7526687',
 '7612333',
 '8606692',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=885256',
 '7115892',
 '9076765',
 '7044756',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=792047',
 '7044768',
 '7030822',
 '8606678',
 '6923711',
 '8967034',
 '7942831',
 '7427130',
 '6906438',
 '7333298',
 '9112052',
 '9873826',
 '9893890',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=970228',
 '7031278',
 '9873802',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1015742',
 '9088902',
 '7427099',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1003013',
 '7341130',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=902485',
 '8016677',
 '5181689',
 '9873785',
 '6923814',
 '8207070',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=876460',
 '9057109',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=892576',
 '7430773',
 '7301142',
 '9104990',
 '9916460',
 '9016985',
 '9901166',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=980056',
 '5181639',
 '7418593',
 '8962943',
 '7107297',
 '8207006',
 '8325690',
 '9873797',
 '7418581',
 '7932587',
 '9916472',
 '9130860',
 '9916458',
 '7717767',
 '8517059',
 '7931757',
 '8311948',
 '9873773',
 '8107529',
 '7828619',
 '8005551',
 '9873814',
 '9901178',
 '7045542',
 '7124427',
 '8722068',
 '6701541',
 '8700541',
 '8834495',
 '6927262',
 '8842624',
 '7630206',
 '8723672',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=712682',
 '8723660',
 '6872792',
 '9906398',
 '8811687',
 '6905032',
 '7724057',
 '9070931',
 '8723232',
 '8811704',
 '7028726',
 '7826099',
 '8847117',
 '9906403',
 '7044811',
 '8718158',
 '7038496',
 '6421763',
 '6707519',
 '8306606',
 '6611198',
 '7415060',
 '7741067',
 '7437991',
 '6521642',
 '9057305',
 '7608784',
 '6800995',
 '8608391',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=832244',
 '7045255',
 '7030339',
 '6919473',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=860066',
 '8723220',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=841525',
 '8811716',
 '6915544',
 '7729942',
 '7226201',
 '8721973',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1003582',
 '7408574',
 '6602848',
 '8729389',
 '8722824',
 '8031172',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=921077',
 '5421077',
 '8724406',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=941189',
 '5026750',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=885294',
 '7725908',
 '9076480',
 '8723024',
 '6900185',
 '7506962',
 '5203920',
 '9847841',
 '7015640',
 '6412877',
 '7303449',
 '7008908',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1303',
 '8606733',
 '8607309',
 '8517126',
 '5206996',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=1003131',
 '7630438',
 '6827345',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=921113',
 '8423612',
 '8131788',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=893869',
 '7534074',
 '6803959',
 '7032753',
 '8725814',
 '8227379',
 '8700175',
 '7941813',
 '5215997',
 '7016864',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=860348',
 '7115921',
 '8725498',
 '7533123',
 '7032765',
 '7034268',
 '7729980',
 '7303487',
 '5423726',
 '6723692',
 '8860119',
 '7124489',
 '8216928',
 '8725486',
 '5156658',
 '6905721',
 '7359254',
 '9878333',
 '7229083',
 '7921344',
 '7921332',
 '9901180',
 '8938289',
 '7833195',
 '7021431',
 '7107651',
 '7362407',
 '7384730',
 'https://lk.rs-class.org/regbook/vessel?fleet_id=876475',
 ...]

In [8]:
df_links = pd.DataFrame(link_all)
df_links

                                                       0
0                                                9916795
1                                                9916800
2      https://lk.rs-class.org/regbook/vessel?fleet_i...
3                                                8227719
4                                                7106657
...                                                  ...
10550  https://lk.rs-class.org/regbook/vessel?fleet_i...
10551  https://lk.rs-class.org/regbook/vessel?fleet_i...
10552  https://lk.rs-class.org/regbook/vessel?fleet_i...
10553  https://lk.rs-class.org/regbook/vessel?fleet_i...
10554                                            9358981

[10555 rows x 1 columns]

In [9]:
#Сохраняем в Excel
writer = pd.ExcelWriter('Суда_links.xlsx')
df_links.to_excel(writer, 'links')
writer.save()

In [44]:
df_links1 = df_links.copy()
df_links1

                                                       0
0                                                9916795
1                                                9916800
2      https://lk.rs-class.org/regbook/vessel?fleet_i...
3                                                8227719
4                                                7106657
...                                                  ...
10550  https://lk.rs-class.org/regbook/vessel?fleet_i...
10551  https://lk.rs-class.org/regbook/vessel?fleet_i...
10552  https://lk.rs-class.org/regbook/vessel?fleet_i...
10553  https://lk.rs-class.org/regbook/vessel?fleet_i...
10554                                            9358981

[10555 rows x 1 columns]

In [45]:
#удаляем ИМО, которые не бьются на сайте
for j in tqdm(range(0, 10555, 1)):
    if len(df_links1[0][j]) < 15:
        df_links1 = df_links1.drop(labels = [j], axis = 0)

100%|██████████████████████████████████████████████████████████████████████████| 10555/10555 [00:04<00:00, 2546.27it/s]

In [2]:
# Загрузка ссылок
df_links1=pd.read_excel('D:\Стас\Ученье - Свет\Оценка\Аспирантура\Видео по NN, Data mining, ABC и т.д\Распределение Гаусса, регрессия\Python\!Наработки\Парсинг по судам/Флитфото.xlsx', sheet_name = 2)
df_links1=df_links1.drop(['№'], axis=1)
df_links1.head(20)

    ИМО (все)                                             Ссылка
0     8722238  https://lk.rs-class.org/regbook/vessel?fleet_i...
1     8969343  https://lk.rs-class.org/regbook/vessel?fleet_i...
2     8521048  https://lk.rs-class.org/regbook/vessel?fleet_i...
3     8722628  https://lk.rs-class.org/regbook/vessel?fleet_i...
4     8138530  https://lk.rs-class.org/regbook/vessel?fleet_i...
5     8722745  https://lk.rs-class.org/regbook/vessel?fleet_i...
6     9312341  https://lk.rs-class.org/regbook/vessel?fleet_i...
7     8661173  https://lk.rs-class.org/regbook/vessel?fleet_i...
8     8728452  https://lk.rs-class.org/regbook/vessel?fleet_i...
9     7702700  https://lk.rs-class.org/regbook/vessel?fleet_i...
10    8722707  https://lk.rs-class.org/regbook/vessel?fleet_i...
11    7808334  https://lk.rs-class.org/regbook/vessel?fleet_i...
12    8228543  https://lk.rs-class.org/regbook/vessel?fleet_i...
13    9056571  https://lk.rs-class.org/regbook/vessel?fleet_i...
14    7349405  https://lk.rs-class.org/regbook/vessel?fleet_i...
15    8227616  https://lk.rs-class.org/regbook/vessel?fleet_i...
16    9116979  https://lk.rs-class.org/regbook/vessel?fleet_i...
17    8225723  https://lk.rs-class.org/regbook/vessel?fleet_i...
18    8826888  https://lk.rs-class.org/regbook/vessel?fleet_i...
19    8834598  https://lk.rs-class.org/regbook/vessel?fleet_i...

In [70]:
df_links1 = df_links1.drop(labels = [291], axis = 0)
len(df_links1)

2963

In [23]:
#это те ссылки, которые я исправил
df_links1=pd.read_excel('D:\Стас\Ученье - Свет\Оценка\Аспирантура\Видео по NN, Data mining, ABC и т.д\Распределение Гаусса, регрессия\Python\!Наработки\Парсинг по судам/доп ссылки.xlsx', sheet_name = 0)
#df_links1=df_links1.drop(['№'], axis=1)
df_links1.head(20)

                                               ссылки
0   https://lk.rs-class.org/regbook/vessel?fleet_i...
1   https://lk.rs-class.org/regbook/vessel?fleet_i...
2   https://lk.rs-class.org/regbook/vessel?fleet_i...
3   https://lk.rs-class.org/regbook/vessel?fleet_i...
4   https://lk.rs-class.org/regbook/vessel?fleet_i...
5   https://lk.rs-class.org/regbook/vessel?fleet_i...
6   https://lk.rs-class.org/regbook/vessel?fleet_i...
7   https://lk.rs-class.org/regbook/vessel?fleet_i...
8   https://lk.rs-class.org/regbook/vessel?fleet_i...
9   https://lk.rs-class.org/regbook/vessel?fleet_i...
10  https://lk.rs-class.org/regbook/vessel?fleet_i...
11  https://lk.rs-class.org/regbook/vessel?fleet_i...
12  https://lk.rs-class.org/regbook/vessel?fleet_i...
13  https://lk.rs-class.org/regbook/vessel?fleet_i...
14  https://lk.rs-class.org/regbook/vessel?fleet_i...
15  https://lk.rs-class.org/regbook/vessel?fleet_i...

In [25]:
n = [] #наименования
z = [] #значения

a = 0

for lnk in tqdm(df_links1['ссылки'], 'Сбор данных'): #перебираем ссылки
    a = a + 1 #счетчик
    
    #этот список будет добавлять в таблицу по тем ссылкам, которые будут выдавать иную таблицу
    #некоторые ссылки выдают иную таблицу, причины не понятны
    l = ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 
         '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
         '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', lnk]
        
    z.clear() #очищаем список значений
        
    driver.get(lnk) #открываем ссылку
    sleep(2) #спим 2 секунды (прогрузка)
        
    soup = BeautifulSoup(driver.page_source, 'lxml') #передаем данный в суп
    for j in range(0, 9): #перебираем первые 9 таблиц, в которых содержатся нужные данные
        try:
            data1 = soup.findAll('table', class_ = 'table')[j].find('tbody').findAll('tr') #перебираем tables, их там 9
        except:
            if j == 8:
                data1 = '99999999'
                continue
            else:
                data1 = '999999'
                continue
        
        for i in data1:
            if a == 1: #выгружаем наименования (шапка таблицы) 1 раз
                dates_n = i.findAll('td')[0].text #выгружаем наименования
                n.append(dates_n) #складываем в словарь 1 раз
            
            try:
                dates_z = i.findAll('td')[1].text #выгружаем значения
                z.append(dates_z) #складываем в словарь
            except:
                dates_z = 0 #выгружаем значения
                z.append(dates_z) #складываем в словарь
                continue 
    #ССЫЛКА значение
    z.append(lnk)
    
    if a == 1: #создаем DF 1 раз, а потом будем к нему добавлять данные, имя столбца будет равно a (счетчик)
        ship_inf = pd.DataFrame(z)
        #ССЫЛКА наименование
        lnk_1 = 'Ссылка'
        n.append(lnk_1)
    
    if a > 1:    
        if len(z) < 56:
            ship_inf[a] = l #если неверная таблица по ссылке, то добавляем список l
        else:    
            ship_inf[a] = z #добавляем в наш DF данные стобцами с именем a (счетчик)

Сбор данных: 100%|█████████████████████████████████████████████████████████████████████| 16/16 [00:45<00:00,  2.86s/it]

In [26]:
ship_inf

,0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,POLA DEVORA,TO CALLISTO,AMUR-2505,ALEKSANDR LEBED,LEONID KHOTKIN,FEOFAN SHOKHIREV,NORTH MOON,BORIS PEVKIN,ALENA,LADY ARZU,ALEXANDRA 1,MILLA,BALTIYSKIY-202,MARAKI,MIKHAIL DUDIN,UNI TRADER
1,090967,632666,842903,855481,886916,887406,891327,896706,905676,906274,913757,914035,932211,941827,950474,980018
2,9471654,5416553,8721313,8866826,8949434,9094157,8829294,8971188,8857772,8903052,8876340,9004487,9057252,9104158,9057329,9175169
3,ПОЛА ДЕВОРА,CALLISTO,АМУР-2505,АЛЕКСАНДР ЛЕБЕДЬ,ЛЕОНИД ХОТЬКИН,ВОЛЖСКИЙ-26,VOLGA-4009,БОРИС ПЕВКИН,АЛЕНА,ЭМЕРАЛЬД 1,ALEXANDRA,STARRY-M,БАЛТИЙСКИЙ-202,RUBIN PEARL,МИХАИЛ ДУДИН,JAGUAR S
4,HOA5354,HP5608,3EZM,3FMB5,3E3526,3EPK9,ЗЕ2562,3EYM7,3E2149,3FHU4,3E2150,3ERE8,3EVM8,ЗЕ2558,3FHO9,3ETF6
5,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама
6,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама,Панама
7,KM* Ice2 (at d<=10.417 m) AUT1 IWS LI bulk car...,(KM)* passenger ship,KM* L3 R2-RSN,KM* L4 R2-RSN,"KM* Ice1 R2-RSN(4,5)",KM* Ice1 R2-RSN,KM(*) L3 [1] R1,"KM* L4 R2-RSN(4,5)",KM* L4 R2-RSN,KM* R1 AUT1,KM* L4 R2-RSN,KM* L1 AUT1,KM* L2 AUT1 INF2,KM* bulk carrier BC-A(ESP) (cargo holds Nos. 2...,KM* L2 AUT3 INF2,KM(*) L3 [1] R1 AUT1 oil tanker(ESP)
8,,,,,,,,,,,,,,,,
9,Навалочное,Пассажирское,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Генгруз,Навалочное,Генгруз,Нефтеналивное
10,18/12/2012,10/12/1963,19/12/1984,30/09/1985,31/05/1989,30/12/1988,25/05/1990,30/07/1989,17/04/1991,01/05/1991,20/11/1991,31/01/1992,02/09/1994,04/07/1994,29/10/1996,30/10/1999
11,Китай,Германия,Чехословакия,СССР,Россия,Россия,СССР,Россия,СССР,Великобритания,СССР,Япония,Россия,Япония,Россия,Россия
12,HH 0802,1104,2305,1015,1029,1028,10,1030,1043,167,1048,1383,202,511,209,302
13,,,,,,,,,,,,,,,,
14,,,,,,,,,,,,,,,,
15,24150 MK-1969,499 MK-1969,2996 MK-1969,4972 MK-1969,4997 MK-1969,4972 MK-1969,4966 MK-1969,4997 MK-1969,4949 MK-1969,2236 MK-1969,4949 MK-1969,6030 MK-1969,2506 MK-1969,15950 MK-1969,2319 MK-1969,4606 MK-1969
16,12150 MK-1969,169 MK-1969,996 MK-1969,2425 MK-1969,2298 MK-1969,2424 MK-1969,1778 MK-1969,2298 MK-1969,2774 MK-1969,1097 MK-1969,2577 MK-1969,3602 MK-1969,1185 MK-1969,9568 MK-1969,1034 MK-1969,2005 MK-1969
17,37390.000 ...,99.000 ...,3340.000 ...,5142.000 ...,5446.000 ...,5376.000 ...,6277.000 ...,5446.000 ...,6059.000 ...,3402.000 ...,6005.000 ...,9597.000 ...,3367.000 ...,26472.000 ...,3030.000 ...,6600.000 ...
18,46912 т.,321 т.,5205 т.,7510 т.,7431 т.,7510 т.,8917 т.,7431 т.,8178 т.,4600 т.,8178 т.,13266 т.,4879 т.,32581 т.,4480 т.,9380 т.
19,189.99 м.,49.98 м.,115.80 м.,139.00 м.,138.30 м.,139.00 м.,139.81 м.,138.30 м.,138.40 м.,99.68 м.,139.00 м.,113.12 м.,89.48 м.,169.51 м.,89.50 м.,129.30 м.
20,189.99 м.,49.98 м.,115.80 м.,-,138.30 м.,139.00 м.,139.81 м.,138.30 м.,138.40 м.,99.68 м.,138.40 м.,113.12 м.,89.48 м.,169.51 м.,89.50 м.,129.30 м.
21,183.00 м.,42.80 м.,109.00 м.,135.00 м.,132.20 м.,130.30 м.,134.00 м.,132.20 м.,136.00 м.,94.38 м.,135.00 м.,106.00 м.,84.90 м.,158.76 м.,84.90 м.,123.20 м.
22,28.50 м.,8.00 м.,13.43 м.,16.70 м.,16.50 м.,16.70 м.,16.56 м.,16.70 м.,16.75 м.,13.26 м.,16.75 м.,18.90 м.,13.43 м.,25.50 м.,13.40 м.,16.50 м.
23,15.10 м.,3.50 м.,6.00 м.,5.50 м.,5.50 м.,5.50 м.,6.70 м.,5.50 м.,5.50 м.,6.35 м.,5.50 м.,11.28 м.,5.50 м.,13.65 м.,5.70 м.,6.80 м.
24,10.40 м.,2.41 м.,4.13 м.,3.78 м.,3.75 м.,3.78 м.,4.68 м.,3.75 м.,4.10 м.,4.44 м.,4.10 м.,8.54 м.,4.88 м.,9.77 м.,4.51 м.,4.98 м.
25,14.0,15.0,10.0,10.6,8.0,10.6,10.0,10.7,10.0,10.0,10.0,14.1,12.0,14.2,11.3,10.5
26,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная,Дизельная
27,Год постройки ГД: 2009Страна постройки: Хорват...,Год постройки ГД: 1963Страна постройки: Герман...,Год постройки ГД: 1983Страна постройки: Чехосл...,Год постройки ГД: 1984Страна постройки: СССРФи...,Год постройки ГД: 1988Страна постройки: Россия...,Год постройки ГД: 1988Страна постройки: СССРФи...,Год постройки ГД: 1987Страна постройки: ГДРФир...,Год постройки ГД: 1988Страна постройки: Россия...,Год постройки ГД: 1991Страна постройки: СССРФи...,Год постройки ГД: 1990Страна постройки: ДанияФ...,Год постройки ГД: 1991Страна постройки: СССРФи...,Год постройки ГД: 1991Страна постройки: Япония...,Год постройки ГД: 1993Страна постройки: Финлян...,Год постройки ГД: 1993Страна постройки: Япония...,Год постройки ГД: 1996Страна постройки: Герман...,Год постройки ГД: 1998Страна постройки: Герман...
28,,,,,,,,,,,,,,,,
29,1 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,2 - Винт фиксированного шага цельнолитой,1 - Винт регулируемого шага,2 - Винт фиксированного шага цельнолитой,1 - Винт регулируемого шага,1 - Винт фиксированного шага цельнолитой,1 - Винт фиксированного шага цельнолитой,1 - Винт фиксированного шага цельнолитой,1 - Винт фиксированного шага цельнолитой
30,4,4,4,4,4,4,3,4,4,4,4,4,4,5,4,4
31,3* 645,2* 200,3* 122 1* 25,2* 100,2* 100 1* 50 ...,2* 100 1* 50,3* 150,2* 100 1* 60 ...,2* 100 1* 50,1* 405 3* 105,2* 100,3* 200 1* 600,2* 160 1* 80,2* 440,2* 160 1* 80,3* 220 1* 110
32,,,,,,,,,,,,,,,,
33,,,,,,,,,,,,,,,,
34,,,,,,,,,,,,,,,,
35,,,,,,,,,,,,,,,,
36,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...,Аппаратура автоматической идентификационной си...
37,1*7589 1*9068 3*10766,,1*874 2*1595,2*2130 1*2245 1*2560 ...,1*1908 1*2738 1*2674 ...,1*2194 1*2315 1*2629 ...,1*1642 1*1701 1*1814 ...,1*1908 1*2738 1*2674 ...,1*2109 1*2843 1*2651 ...,1*2404 1*2081,1*2112 1*2524 1*2335 ...,1*12005,1*1670 1*1660,1*4855 1*7905 1*8035 ...,1*1730 1*1690,
38,,,,,,,,,,,,,,,,
39,,,,,,,,,,,,,,,,10* 7384
40,,,102,,,,,,,,,64,120,,136,
41,1,5,1,1,1,1,1,1,1,2,2,2,1,1,1,1
42,7,6,8,7,8,10,11,8,9,4,10,4,4,7,5,8
43,0,34,0,0,0,0,0,0,0,0,0,0,0,,0,0
44,0,0,0,0,0,0,0,0,0,0,0,0,0,,0,0
45,0,0,0,0,0,0,0,0,0,0,0,0,0,,0,0
46,D 1 - 16.0*16.0D 1 - 21.6*18.0D 3 - 22.4*18.0,,1 - 14.1*10.1 2 - 25.3*10.1,2 - 21.5*13.6 2 - 18.6*13.6,1 - 13.2*18.1 1 - 13.2*25.3 1 - 13.2*24.7 1 -...,2 - 18.7*13.6 2 - 21.6*13.6,4 - 18.7*11.8,1 - 13.2*18.1 1 - 13.2*25.3 1 - 13.2*24.7 1 -...,2 - 19.8*13.3 1 - 23.7*13.3 1 - 21.9*13.3,1 - 37.9*10.2 1 - 30.0*10.2,2 - 13.3*19.8 1 - 13.3*23.7 1 - 13.3*21.9,1 - 33.6*15.7 1 - 35.7*15.7,2 - 10.6*25.0,D 1 - 12.8*16.0D 4 - 19.2*17.6,2 - 25.0*10.6,
47,1*7.0 1*3.0,,,,,,,,,,,,,,,
48,4*30.0 1*3.0,,,,,,,,,,,,,4*30.5,,1*2.0
49,22043,21,144,145,160,162,417,160,137,111,188,796,240,1142,149,308
50,"Дизельное, Мазут",Дизельное,Дизельное,Дизельное,Дизельное,Дизельное,"Дизельное, Моторное",Дизельное,"Дизельное, Моторное",Дизельное,Дизельное,"Дизельное, Моторное",Дизельное,"Дизельное, Мазут","Дизельное, Моторное","Дизельное, Мазут"
51,24081 m3,26 m3,2002 m3,3101 m3,3244 m3,3102 m3,2186 m3,3244 m3,3158 m3,1852 m3,3158 m3,2200 m3,1009 m3,7384 m3,1101 m3,3636 m3
52,,,,,,,ПТ,,,,,ПТ,,,ПТ,ПТПГ
53,2450,205,700,708,537,709,717,537,617,450,775,1256,700,,660,874
54,Особой прочности,Обыкновенная,Обыкновенная,Обыкновенная,Обыкновенная,Повышенной прочности,Повышенной прочности,Повышенной прочности,Обыкновенная,Повышенной прочности,Обыкновенная,Повышенной прочности,Обыкновенная,Обыкновенная,Повышенной прочности,Повышенной прочности
55,66.0,26.0,46.0,44.0,44.0,44.0,44.0,44.0,44.0,34.0,44.0,50.0,45.0,68.0,40.0,46.0
56,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...,https://lk.rs-class.org/regbook/vessel?fleet_i...

In [27]:
ship_inf = ship_inf.transpose()
ship_inf

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,POLA DEVORA,090967,9471654,ПОЛА ДЕВОРА,HOA5354,Панама,Панама,KM* Ice2 (at d<=10.417 m) AUT1 IWS LI bulk car...,,Навалочное,...,1*7.0 1*3.0,4*30.0 1*3.0,22043,"Дизельное, Мазут",24081 m3,,2450,Особой прочности,66.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
2,TO CALLISTO,632666,5416553,CALLISTO,HP5608,Панама,Панама,(KM)* passenger ship,,Пассажирское,...,,,21,Дизельное,26 m3,,205,Обыкновенная,26.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
3,AMUR-2505,842903,8721313,АМУР-2505,3EZM,Панама,Панама,KM* L3 R2-RSN,,Генгруз,...,,,144,Дизельное,2002 m3,,700,Обыкновенная,46.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
4,ALEKSANDR LEBED,855481,8866826,АЛЕКСАНДР ЛЕБЕДЬ,3FMB5,Панама,Панама,KM* L4 R2-RSN,,Генгруз,...,,,145,Дизельное,3101 m3,,708,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
5,LEONID KHOTKIN,886916,8949434,ЛЕОНИД ХОТЬКИН,3E3526,Панама,Панама,"KM* Ice1 R2-RSN(4,5)",,Генгруз,...,,,160,Дизельное,3244 m3,,537,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
6,FEOFAN SHOKHIREV,887406,9094157,ВОЛЖСКИЙ-26,3EPK9,Панама,Панама,KM* Ice1 R2-RSN,,Генгруз,...,,,162,Дизельное,3102 m3,,709,Повышенной прочности,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
7,NORTH MOON,891327,8829294,VOLGA-4009,ЗЕ2562,Панама,Панама,KM(*) L3 [1] R1,,Генгруз,...,,,417,"Дизельное, Моторное",2186 m3,ПТ,717,Повышенной прочности,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
8,BORIS PEVKIN,896706,8971188,БОРИС ПЕВКИН,3EYM7,Панама,Панама,"KM* L4 R2-RSN(4,5)",,Генгруз,...,,,160,Дизельное,3244 m3,,537,Повышенной прочности,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
9,ALENA,905676,8857772,АЛЕНА,3E2149,Панама,Панама,KM* L4 R2-RSN,,Генгруз,...,,,137,"Дизельное, Моторное",3158 m3,,617,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
10,LADY ARZU,906274,8903052,ЭМЕРАЛЬД 1,3FHU4,Панама,Панама,KM* R1 AUT1,,Генгруз,...,,,111,Дизельное,1852 m3,,450,Повышенной прочности,34.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
11,ALEXANDRA 1,913757,8876340,ALEXANDRA,3E2150,Панама,Панама,KM* L4 R2-RSN,,Генгруз,...,,,188,Дизельное,3158 m3,,775,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
12,MILLA,914035,9004487,STARRY-M,3ERE8,Панама,Панама,KM* L1 AUT1,,Генгруз,...,,,796,"Дизельное, Моторное",2200 m3,ПТ,1256,Повышенной прочности,50.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
13,BALTIYSKIY-202,932211,9057252,БАЛТИЙСКИЙ-202,3EVM8,Панама,Панама,KM* L2 AUT1 INF2,,Генгруз,...,,,240,Дизельное,1009 m3,,700,Обыкновенная,45.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
14,MARAKI,941827,9104158,RUBIN PEARL,ЗЕ2558,Панама,Панама,KM* bulk carrier BC-A(ESP) (cargo holds Nos. 2...,,Навалочное,...,,4*30.5,1142,"Дизельное, Мазут",7384 m3,,,Обыкновенная,68.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
15,MIKHAIL DUDIN,950474,9057329,МИХАИЛ ДУДИН,3FHO9,Панама,Панама,KM* L2 AUT3 INF2,,Генгруз,...,,,149,"Дизельное, Моторное",1101 m3,ПТ,660,Повышенной прочности,40.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
16,UNI TRADER,980018,9175169,JAGUAR S,3ETF6,Панама,Панама,KM(*) L3 [1] R1 AUT1 oil tanker(ESP),,Нефтеналивное,...,,1*2.0,308,"Дизельное, Мазут",3636 m3,ПТПГ,874,Повышенной прочности,46.0,https://lk.rs-class.org/regbook/vessel?fleet_i...

In [28]:
ship_n = pd.DataFrame(n)
ship_n = ship_n.transpose()
ship_n

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,Название судна,Регистровый номер,Номер ИМО,Бывшее название,Позывной,Порт приписки,Флаг,Символ класса,Переоборудование/модернизация существенного ха...,Основной тип,...,Стрелы,Краны,Запасы топлива,Типы топлива,Водяной балласт,Подогреватели,Характеристика снабжения,Категория якорных цепей,Калибр якорных цепей,Ссылка

In [29]:
#result = pd.concat([ship_n, ship_inf], axis=1)
result = pd.concat([ship_n, ship_inf])
result

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,Название судна,Регистровый номер,Номер ИМО,Бывшее название,Позывной,Порт приписки,Флаг,Символ класса,Переоборудование/модернизация существенного ха...,Основной тип,...,Стрелы,Краны,Запасы топлива,Типы топлива,Водяной балласт,Подогреватели,Характеристика снабжения,Категория якорных цепей,Калибр якорных цепей,Ссылка
0,POLA DEVORA,090967,9471654,ПОЛА ДЕВОРА,HOA5354,Панама,Панама,KM* Ice2 (at d<=10.417 m) AUT1 IWS LI bulk car...,,Навалочное,...,1*7.0 1*3.0,4*30.0 1*3.0,22043,"Дизельное, Мазут",24081 m3,,2450,Особой прочности,66.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
2,TO CALLISTO,632666,5416553,CALLISTO,HP5608,Панама,Панама,(KM)* passenger ship,,Пассажирское,...,,,21,Дизельное,26 m3,,205,Обыкновенная,26.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
3,AMUR-2505,842903,8721313,АМУР-2505,3EZM,Панама,Панама,KM* L3 R2-RSN,,Генгруз,...,,,144,Дизельное,2002 m3,,700,Обыкновенная,46.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
4,ALEKSANDR LEBED,855481,8866826,АЛЕКСАНДР ЛЕБЕДЬ,3FMB5,Панама,Панама,KM* L4 R2-RSN,,Генгруз,...,,,145,Дизельное,3101 m3,,708,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
5,LEONID KHOTKIN,886916,8949434,ЛЕОНИД ХОТЬКИН,3E3526,Панама,Панама,"KM* Ice1 R2-RSN(4,5)",,Генгруз,...,,,160,Дизельное,3244 m3,,537,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
6,FEOFAN SHOKHIREV,887406,9094157,ВОЛЖСКИЙ-26,3EPK9,Панама,Панама,KM* Ice1 R2-RSN,,Генгруз,...,,,162,Дизельное,3102 m3,,709,Повышенной прочности,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
7,NORTH MOON,891327,8829294,VOLGA-4009,ЗЕ2562,Панама,Панама,KM(*) L3 [1] R1,,Генгруз,...,,,417,"Дизельное, Моторное",2186 m3,ПТ,717,Повышенной прочности,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
8,BORIS PEVKIN,896706,8971188,БОРИС ПЕВКИН,3EYM7,Панама,Панама,"KM* L4 R2-RSN(4,5)",,Генгруз,...,,,160,Дизельное,3244 m3,,537,Повышенной прочности,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
9,ALENA,905676,8857772,АЛЕНА,3E2149,Панама,Панама,KM* L4 R2-RSN,,Генгруз,...,,,137,"Дизельное, Моторное",3158 m3,,617,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
10,LADY ARZU,906274,8903052,ЭМЕРАЛЬД 1,3FHU4,Панама,Панама,KM* R1 AUT1,,Генгруз,...,,,111,Дизельное,1852 m3,,450,Повышенной прочности,34.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
11,ALEXANDRA 1,913757,8876340,ALEXANDRA,3E2150,Панама,Панама,KM* L4 R2-RSN,,Генгруз,...,,,188,Дизельное,3158 m3,,775,Обыкновенная,44.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
12,MILLA,914035,9004487,STARRY-M,3ERE8,Панама,Панама,KM* L1 AUT1,,Генгруз,...,,,796,"Дизельное, Моторное",2200 m3,ПТ,1256,Повышенной прочности,50.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
13,BALTIYSKIY-202,932211,9057252,БАЛТИЙСКИЙ-202,3EVM8,Панама,Панама,KM* L2 AUT1 INF2,,Генгруз,...,,,240,Дизельное,1009 m3,,700,Обыкновенная,45.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
14,MARAKI,941827,9104158,RUBIN PEARL,ЗЕ2558,Панама,Панама,KM* bulk carrier BC-A(ESP) (cargo holds Nos. 2...,,Навалочное,...,,4*30.5,1142,"Дизельное, Мазут",7384 m3,,,Обыкновенная,68.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
15,MIKHAIL DUDIN,950474,9057329,МИХАИЛ ДУДИН,3FHO9,Панама,Панама,KM* L2 AUT3 INF2,,Генгруз,...,,,149,"Дизельное, Моторное",1101 m3,ПТ,660,Повышенной прочности,40.0,https://lk.rs-class.org/regbook/vessel?fleet_i...
16,UNI TRADER,980018,9175169,JAGUAR S,3ETF6,Панама,Панама,KM(*) L3 [1] R1 AUT1 oil tanker(ESP),,Нефтеналивное,...,,1*2.0,308,"Дизельное, Мазут",3636 m3,ПТПГ,874,Повышенной прочности,46.0,https://lk.rs-class.org/regbook/vessel?fleet_i...

In [30]:
#Сохраняем в Excel
writer = pd.ExcelWriter('Суда_инф_доп.xlsx')
result.to_excel(writer, 'inf')
writer.save()

In [71]:
#ПРИМЕР через selenium
#Вытаскиваем данные
data_all = []

infa = ['Общие сведения',
       'Тип судна',
       'Сведения о постройке',
       'Размеры и скорость',
       'Механизмы',
       'Холодильная установка и радио-навигационное оборудование',
       'Трюма, палубы, пассажиры',
       'Люки, стрелы, краны',
       'Запасы и снабжение'
      ]

for inf in infa:
    #driver.find_element_by_link_text(inf).click() #переходим на infa
    driver.find_element_by_link_text(inf).send_keys(Keys.ENTER) #може и так осуществить переход
    data = driver.find_elements_by_class_name('tab-content') #Находим родительский класс, где все лежит и выгружаем текст
    data
    #data = driver.find_elements_by_class_name('table')
    for i in data: #перебираем текст
        print(i.text) #принтим текст
        data_all.append(i.text) #складываем текст в массив

C:\Users\skapr\AppData\Local\Temp\ipykernel_21896\2344182724.py:17: DeprecationWarning: find_element_by_link_text is deprecated. Please use find_element(by=By.LINK_TEXT, value=link_text) instead
  driver.find_element_by_link_text(inf).send_keys(Keys.ENTER) #може и так осуществить переход
C:\Users\skapr\AppData\Local\Temp\ipykernel_21896\2344182724.py:18: DeprecationWarning: find_elements_by_class_name is deprecated. Please use find_elements(by=By.CLASS_NAME, value=name) instead
  data = driver.find_elements_by_class_name('tab-content') #Находим родительский класс, где все лежит и выгружаем текст

Название судна БИЛИБИНО
Регистровый номер 886140
Номер ИМО 8801632
Бывшее название ФЕСКО ПРИМОРЬЕ
Позывной UEDL
Порт приписки Анадырь
Флаг Россия
Символ класса KM* L1
Переоборудование/модернизация существенного характера
Основной тип Генгруз
Дата постройки 19/08/1989
Страна постройки Япония
Строительный номер 1334
Дата значительной части
Значительная часть
Валовая вместимость 6030 MK-1969
Чистая вместимость 3602 MK-1969
Дедвейт 9590.000 т.
Водоизмещение 13266 т.
Длина габаритная 113.12 м.
Длина наибольшая (теоретическая) 113.12 м.
Длина расчетная 106.00 м.
Ширина габаритная 19.20 м.
Высота борта 11.28 м.
Осадка 8.54 м.
Скорость 14.1
Тип силовой установки Дизельная
Главные двигатели
Год постройки ГД: 1989
Страна постройки: Япония
Фирма постройки ГД: HANSHIN DIESEL WORKS LTD
Количество и мощность ГД: 1*4413
Марка ГД: 6LF58
Количество и мощность ГЭД
Количество и тип движителя 1 - Винт регулируемого шага
Количество лопастей 4
Количество и мощность генераторов 1* 600 3* 200 1* 58
Главные котлы
Холодильная установка
Рабочая температура
Хладагенты
Радио-навигационное оборудование Гирокомпас
Командно-трансляционное устройство
Лаг (тоже - ЛГЭ)
Магнитный компас
Оборудование системы опознавания судов и слежения за ними на дальнем расстоянии
ПВ/КВ радиоустановка (ПВ/КВ радиотелефонная станция с цифровым избирательным вызовом и УБПЧ)
Приемник расширенного группового вызова
Приемник службы НАВТЕКС
Радиолокационная станция (тоже - РЛ)
Радиолокационный ответчик, Передатчик АИС для целей поиска и спасания
Система контроля дееспособности вахтенного помощника капитана
Спутниковый аварийный радиобуй системы КОСПАС-САРСАТ
Средство автоматической радиолокационной прокладки
Судовая земная станция системы ГМССБ
Судовая система охранного оповещения
УКВ аппаратура двусторонней радиотелефонной связи
УКВ радиоустановка (УКВ радиотелефонная станция с цифровым избирательным вызовом)
Упрощенный регистратор данных рейса
Эхолот
Количество и кубатура грузовых трюмов 1*12738
Охлаждаемые грузовые помещения
Наливные танки
Количество и тип контейнеров 500
Количество палуб 1
Количество переборок 3
Число пассажиров коечные 0
Число пассажиров бескоечных 0
Спецперсонал 0
Грузовые люки (число и размер в свету) 1 - 33.6*15.7 1 - 35.7*15.7
Стрелы
Краны 2*50.0
Запасы топлива 712
Типы топлива Дизельное, Мазут
Водяной балласт 2256 m3
Подогреватели
Характеристика снабжения 1250
Категория якорных цепей Повышенной прочности
Калибр якорных цепей 56.0